from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from calibration.profile import CalibrationProfile, ProfileError


def generate_json(profile: CalibrationProfile) -> str:
    profile.validate_semantics()
    return (
        json.dumps(profile.to_json(), sort_keys=True, indent=2, ensure_ascii=False)
        + "\n"
    )


def generate_csharp(
    profile: CalibrationProfile,
    *,
    namespace: str = "AAInteractiveValueAnalyzer.Client.Models",
) -> str:
    profile.validate_semantics()
    encoded = generate_json(profile).rstrip()
    return f'''// <auto-generated />
// Profile hash: {profile.profile_hash}
namespace {namespace};

internal static class GeneratedCalibrationProfile
{{
    public const string ProfileHash = "{profile.profile_hash}";
    public static CalibrationProfile Value {{ get; }} = CalibrationProfile.FromJson(Json);
    private const string Json = """
{encoded}
""";
}}
'''


def write_application_artifacts(
    profile: CalibrationProfile,
    directory: str | Path,
    *,
    namespace: str = "AAInteractiveValueAnalyzer.Client.Models",
) -> tuple[Path, Path]:
    root = Path(directory)
    root.mkdir(parents=True, exist_ok=True)
    json_path = root / "calibration-profile.generated.json"
    csharp_path = root / "CalibrationProfile.generated.cs"
    json_content = generate_json(profile)
    csharp_content = generate_csharp(profile, namespace=namespace)
    for path, content in ((json_path, json_content), (csharp_path, csharp_content)):
        if path.exists() and path.read_text(encoding="utf-8") != content:
            raise ProfileError(f"Generated artifact cannot be overwritten: {path}")
        path.write_text(content, encoding="utf-8")
    return json_path, csharp_path


def format_number(value: Any) -> str:
    if value is None:
        return "null"
    number = float(value)
    if number.is_integer():
        return f"{number:.1f}d"
    return f"{number:.17g}d"
