from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from calibration.profile import CalibrationProfile, ProfileError


def generate_json(profile: CalibrationProfile) -> str:
    profile.validate_semantics()
    return json.dumps(profile.to_json(), sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def generate_csharp(profile: CalibrationProfile, *, namespace: str = "AAInteractiveValueAnalyzer.Client.Models") -> str:
    profile.validate_semantics()
    segments = ",\n            ".join(
        f"new CurveSegment({format_number(segment['upper'])}, {format_number(segment['slope'])})"
        for segment in profile.curve_segments
    )
    tau = ",\n            ".join(
        f"[\"{key}\"] = {format_number(value)}"
        for key, value in sorted(profile.tau.items())
    )
    return f'''// <auto-generated />
// Profile hash: {profile.profile_hash}
using System.Collections.Generic;

namespace {namespace};

public sealed record CalibrationProfile(
    string ProfileVersion,
    string ProfileHash,
    IReadOnlyList<CurveSegment> CurveSegments,
    IReadOnlyDictionary<string, double> Tau,
    double ErrorFloor,
    string FittingDataHash,
    string AaSnapshot)
{{
    public static CalibrationProfile Generated {{ get; }} = new(
        "{profile.profile_version}",
        "{profile.profile_hash}",
        new[]
        {{
            {segments}
        }},
        new Dictionary<string, double>
        {{
            {tau}
        }},
        {format_number(profile.error_floor)},
        "{profile.fitting_data_hash}",
        "{profile.aa_snapshot}");
}}

public readonly record struct CurveSegment(double? Upper, double Slope);
'''


def write_application_artifacts(
    profile: CalibrationProfile,
    directory: str | Path,
    *,
    namespace: str = "AAInteractiveValueAnalyzer.Client.Models",
) -> tuple[Path, Path]:
    root = Path(directory)
    root.mkdir(parents=True, exist_ok=True)
    json_path = root / "calibration-profile.generated.json"
    csharp_path = root / "CalibrationProfile.generated.cs"
    json_content = generate_json(profile)
    csharp_content = generate_csharp(profile, namespace=namespace)
    for path, content in ((json_path, json_content), (csharp_path, csharp_content)):
        if path.exists() and path.read_text(encoding="utf-8") != content:
            raise ProfileError(f"Generated artifact cannot be overwritten: {path}")
        path.write_text(content, encoding="utf-8")
    return json_path, csharp_path


def format_number(value: Any) -> str:
    if value is None:
        return "null"
    number = float(value)
    if number.is_integer():
        return f"{number:.1f}d"
    return f"{number:.17g}d"
